### ISSUE TITLE
open: Files are not opened and error message is shown

### ISSUE THREAD

**Issue by infeo** [cryptomator/fuse-nio-adapter#10]
## Basic Info
OS: Windows 10
branch: feature/cryptofsIntegration
commit: 426439babe55fcad0e9631e6c263c39b0fd941ff 

## Description
Some applications have problems open files in the vault. They must be copied from the vault to a place outside the vault to open them in the specific program. Currently it is unclear, if it depends on the application or not. It does not depend on the file-type.

Steps to Reproduce:
1 Have an exisiting vault with for example a pdf-file in it.
1 Open the "open-with"-dialogue and select microsoft edge

**Expected Result:** The file is shown in the program
**Actual Result:** An empty file and/or an error message is shown

##Examples:
.pdf-files and Microsoft Edge
.txt-files or .odt-files and Wordpad

**Comment by overheadhunter** [comment]
Closing this, as we no longer aim to support Windows. We're moving to [dokany-nio-adapter](https://github.com/cryptomator/dokany-nio-adapter).
