### ISSUE TITLE
delete: Slow on Windows

### ISSUE THREAD

**Issue by infeo** [cryptomator/fuse-nio-adapter#11]
## Basic Info
OS: Windows 10
branch: feature/cryptofsIntegration
commit: 426439babe55fcad0e9631e6c263c39b0fd941ff 

## Description
Deleting a directory with a lot of small files in it takes a long time to finish. My test directory contains 432 files, every file has an average file size of 17 KB. It takes nearly 4 minutes to delete the directory. Under Linux the deletion is executed within seconds.

**Comment by billziss-gh** [comment]
In Windows deleting a file is an involved process:

- **OPEN**: Open the file or directory (`open` or `opendir`).
- **SET DISPOSITION**: Set the "disposition" flag, which marks the file as pending delete. This happens internally to the FUSE layer and is not visible to a FUSE file system, except in the case of a directory where you will receive a `readdir` to verify that the directory is empty.
- **CLEANUP**: "Cleanup" the file. Windows expects the file system to actually delete the file at this point. The FUSE layer issues an `unlink` or `rmdir` accordingly.
    - **NOTE**: Cleanup cannot report failures, which means that if the `unlink` or `rmdir` fails for any reason, the failure will **NOT** be reported to the caller! This is an unfortunate consequence of the Windows file delete method combined with that in FUSE. The idea is that at the point the file system receives the Cleanup, the file system has **committed** to delete the file (during the "disposition" phase), which unfortunately does not match FUSE behavior.
- **CLOSE**: Close the file or directory (`close` or `closedir`).

As can be seen deleting a file in Windows is an involved process and certainly more involved than POSIX. For this reason Windows file delete will be slower in general than POSIX file delete.

However I would expect 400+ files to be deleted in 1-2 seconds, which perhaps points to another problem in your file system (e.g. perhaps there is some unnecessary caching during `open`).

**Comment by infeo** [comment]
Well, that really sounds like some (more or less) time consuming work. My guess is, that it's the encryption/decryption operation which slows the process in such a way down, because encryption is on the fly. If it`s not cached, then each call needs an decryption operation und so for deleting one file at least 4 decryption ops are executed
Addtionally in my case it could be driver issue because i tested it on a nvme-ssd.
On antoher system with a normal ssd, it took 2min and 30s.

**Comment by billziss-gh** [comment]
> My guess is, that it's the encryption/decryption operation which slows the process in such a way down, because encryption is on the fly. If it`s not cached, then each call needs an decryption operation und so for deleting one file at least 4 decryption ops are executed

I do not understand the details of your file system so my comments may be off.

The encryption/decryption operation is certainly needed, but I would make sure that only file metadata gets encrypted/decrypted and not file data. For example, if there is an initial fetch of any data during `open` that should be eliminated, and should only happen on the first `read` or `write`. Furthermore upon opening the file any metadata that is read, should probably be cached (at least for some time), in case you get a quick `getattr` or `unlink` and then `release`. Windows always opens files in order to work with them, so you will see a lot of superfluous opens.

**Comment by overheadhunter** [comment]
Closing this, as we no longer aim to support Windows. We're moving to [dokany-nio-adapter](https://github.com/cryptomator/dokany-nio-adapter).
