### ISSUE TITLE
Check compatibility

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/fuse-nio-adapter#18]
Minimum version of FUSE for macOS should be checked, see https://github.com/cryptomator/cryptomator/issues/657.

**Comment by overheadhunter** [comment]
According to [this issue](https://github.com/osxfuse/osxfuse/issues/175) the best way to get the "FUSE for macOS " version is by invoking `const char *osxfuse_version(void)` after loading `libosxfuse.dylib`.

Using JNR this could look like this:

```java
public class FuseForMacVersionChecker {

	private static final String DYLIB_NAME = "osxfuse";

	public Optional<String> getVersion() {
		try {
			FuseDarwin lib = LibraryLoader.create(FuseDarwin.class).load(DYLIB_NAME);
			return Optional.of(lib.osxfuse_version());
		} catch (UnsatisfiedLinkError e) {
			return Optional.empty();
		}
	}

	// see /usr/local/include/osxfuse/fuse/fuse_darwin.h
	public interface FuseDarwin {
		String osxfuse_version();
	}
}
```

However, the library is already loaded via jnr-fuse, so maybe they can provide such a method...?

**Comment by infeo** [comment]
Another possibility is to parse the file `/Library/Filesystms/osxfuse.fs/Contents/version.plist`. In this file the version of the installed osxfuse bundle is listed.
**The good thing** about this way is that we don't need to load the library ourself. 
**The bad thing** is that we need read access to this file.
