### ISSUE TITLE
Improve performance with `negative_vncache` option

### ISSUE THREAD

**Issue by infeo** [cryptomator/fuse-nio-adapter#22]
On MacOS we are using the fuse api provided by the https://github.com/osxfuse/osxfuse project.

A mount option of this library is `negative_vncache`, which lets the kernel save not existing files upon their first LOOKUP call and does not bother the fuse-filesystem with calls to these files.

Since we are using the mount-class specifically for https://github.com/cryptomator/cryptomator and due to its architecture we could use this option to increase performance, assuming that files can only be added when a vault is unlocked

**Comment by overheadhunter** [comment]
Files can be added via sync, though.

**Comment by infeo** [comment]
That... is true.
