### ISSUE TITLE
Set f_namemax in statfs

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/fuse-nio-adapter#23]
As an attempt to fix cryptomator/cryptomator#770, we should set `f_namemax` in the [struct returned by `statfs`](https://github.com/cryptomator/fuse-nio-adapter/blob/1.0.1/src/main/java/org/cryptomator/frontend/fuse/ReadOnlyAdapter.java#L67).

https://github.com/cryptomator/fuse-nio-adapter/blob/2831059d290dcd00a708e2e05c39f5aef91a6abf/src/main/java/org/cryptomator/frontend/fuse/ReadOnlyAdapter.java#L66-L84

Whether this fix works can be verified using a mirrored directory by invoking `getconf _POSIX_NAME_MAX /some/path` on the shell.

**Comment by purejava** [comment]
A value of `255` seams [reasonable](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits) for linux file systems.

FUSE is not in the list, but `255` seams to be the [right value for FUSE](https://github.com/libfuse/libfuse/blob/master/lib/fuse_lowlevel.c#L1513) too.

**Comment by purejava** [comment]
I saw that @infeo was assigned for this issue. If it's ok, I would propose something.

**Comment by overheadhunter** [comment]
@purejava yes, please proceed 🙂

**Comment by purejava** [comment]
You are very welcome @infeo. All fuse-nio-adapter maven tests passed as well.
Did not mention that, but of course compiling with maven is part of the basic tests that are required on every change.

**Comment by purejava** [comment]
And thank you too @overheadhunter for reviewing and merging that quickly!
