### ISSUE TITLE
Support for extended attributes (xattr)

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/fuse-nio-adapter#35]
Once cryptomator/cryptofs#47 is fixed, we can support xattrs. Regarding error codes, we should stick to [the osx manpage](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setxattr.2.html), which has a more detailed distinction between different errors. 

Noteworthy: `E2BIG` and `ENAMETOOLONG` should be handled correctly, since the size might increase due to the encryption layer.

**Comment by infeo** [comment]
Closed in 2cb7a28afd61bad626469f962ae5d5b78a232225

> Once https://github.com/cryptomator/cryptofs/issues/47 is fixed, we can support xattrs

Since this is a different project, we already implemented in this layer the xattr support, but return the "ENOTSUP" if the underlying java filesystem not support `UserDefinedAttributeView`.
