### ISSUE TITLE
How to use it to launch custom nio filesystem?

### ISSUE THREAD

**Issue by xiptos** [cryptomator/fuse-nio-adapter#39]
Not really an issue, but I don't seem to find any clue. How do I mount a custom filesystem?
I'm trying this:
```Java
public static void main(String[] args) throws CommandFailedException {
        Mounter mounter = FuseMountFactory.getMounter();
        mounter.mount(Paths.get(URI.create("pdinfs:mem:/")), EnvironmentVariables.create().withMountPoint(Paths.get("/tmp/mnt")).build());
    }
```

and I'm getting:
```
Exception in thread "main" org.cryptomator.frontend.fuse.mount.CommandFailedException: java.lang.NullPointerException
	at org.cryptomator.frontend.fuse.mount.MacMounter.mount(MacMounter.java:42)
	at pt.ipb.pdinfs.Main.main(Main.java:14)
Caused by: java.lang.NullPointerException
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:252)
	at org.cryptomator.frontend.fuse.mount.MacMounter.mount(MacMounter.java:40)
	... 1 more
```

What am I doing wrong?

**Comment by xiptos** [comment]
I believe I found the first problem:
```Java
Mounter mounter = FuseMountFactory.getMounter();
        mounter.mount(Paths.get(URI.create("pdinfs:mem:/")), EnvironmentVariables.create().withMountPoint(Paths.get("file:/tmp/mnt")).withFlags(new String[]{}).build());
```
Flags cannot be `null`.

**Comment by overheadhunter** [comment]
Add fuseflags to `EnvironmentVariables`. This can be an empty array.

We need to fix both, documentation and parameter checks.

**Comment by xiptos** [comment]
Now I'm having some issue that I can't understand. After mounting I get:
```
ls: mnt: Device not configured
```
I have no clue why... is this fuse problem or my code?
The operating system is MacOS with osxfuse.

**Comment by overheadhunter** [comment]
What does the log say?

**Comment by xiptos** [comment]
How can I activate the logs and where can I see it?

**Comment by overheadhunter** [comment]
I can't tell you that, as it depends on the logger you're using in your project. This lib logs via the slf4j API. That's all I can tell you.

Your aforementioned issue is legitimate, however this is not the right place to get help with your project.

**Comment by xiptos** [comment]
I understand, sure. I tried to configure the log level in logback.xml, but it didn't show any messages related to the org.cryptomator package. My project is still in early infancy here: [https://gitlab.estig.ipb.pt/rlopes/pdinfs](https://gitlab.estig.ipb.pt/rlopes/pdinfs).
Thank you very much @overheadhunter, and sorry for the noise...

**Comment by overheadhunter** [comment]
I see, then setting the log level to TRACE in logback.xml should work.

```xml
<logger name="org.cryptomator" level="TRACE" />
```

You should at least see logs regarding the different fs methods (`fsstat`, `readdir`, `readattr`, etc). This should give you a clue, which of these methods has been called before `ls` failed. Probably the returned result of this method didn't satisfy `ls`.

**Comment by xiptos** [comment]
Thank you again, Sebastian

After setting the trace level I got this:

This is mine. It means that FUSE is expecting the PosixFileAttributeView and it is not implemented by my filesystem, so returns false:
18:30:01.046 [Thread-3] DEBUG pt.ipb.pdinfs.nio.PDinFileStore - AttributeViewSupport to [interface java.nio.file.attribute.PosixFileAttributeView] = false

This is fuse-nio-adapter:
18:30:01.046 [Thread-3] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2019-11-20T12:30:00.538861Z, lastAccessTime: 2019-11-20T12:30:00.538861Z, creationTime: 2019-11-20T12:30:00.538861Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 0, fileKey: null)
18:30:01.048 [Thread-3] TRACE o.c.f.fuse.locks.DataRLockImpl - Released read data lock for '[]'
18:30:01.048 [Thread-3] TRACE o.c.f.fuse.locks.PathRLockImpl - Released read path lock for '[]'
18:30:02.971 [Thread-0] DEBUG o.c.frontend.fuse.ReadOnlyAdapter - Marked file system adapter as unmounted.

Could it have something to do with the fact that the fileKey is null?
It seems that the filesystem is immediately umounted.

Sorry…

/rp

**Comment by overheadhunter** [comment]
No, the filekey is never used. Neither [here](https://github.com/cryptomator/fuse-nio-adapter/blob/3ebb29e0801c980b51a47df3d2c7d768eebe197d/src/main/java/org/cryptomator/frontend/fuse/ReadOnlyDirectoryHandler.java#L34-L45) nor [here](https://github.com/cryptomator/fuse-nio-adapter/blob/3ebb29e0801c980b51a47df3d2c7d768eebe197d/src/main/java/org/cryptomator/frontend/fuse/FileAttributesUtil.java#L51-L80).

However, this line...

```
18:30:02.971 [Thread-0] DEBUG o.c.frontend.fuse.ReadOnlyAdapter - Marked file system adapter as unmounted.
```

... suggests that you immediately unmounted the file system after mounting it. When looking at your code, I think this is because your `main` method just "ends".

One way to keep the main thread running is to wait for user input as done here:

https://github.com/cryptomator/fuse-nio-adapter/blob/3ebb29e0801c980b51a47df3d2c7d768eebe197d/src/test/java/org/cryptomator/frontend/fuse/mount/MirroringFuseMountTest.java#L133-L141

(Note the `System.in.read();`)

**Comment by xiptos** [comment]
Yes… good catch.
However, I still have the same result:

19:13:13.635 [Thread-3] TRACE o.c.frontend.fuse.locks.LockManager - Creating ReadWriteLock for []
19:13:13.642 [Thread-3] TRACE o.c.f.fuse.locks.PathRLockImpl - Acquired read path lock for '[]'
19:13:13.642 [Thread-3] TRACE o.c.frontend.fuse.locks.LockManager - Creating ReadWriteLock for []
19:13:13.642 [Thread-3] TRACE o.c.f.fuse.locks.DataRLockImpl - Acquired read data lock for '[]'
19:13:13.648 [Thread-3] DEBUG pt.ipb.pdinfs.nio.PDinFileStore - AttributeViewSupport to [interface java.nio.file.attribute.PosixFileAttributeView] = false
19:13:13.648 [Thread-3] TRACE o.c.frontend.fuse.ReadOnlyAdapter - getattr / (lastModifiedTime: 2019-11-20T13:13:13.074328Z, lastAccessTime: 2019-11-20T13:13:13.074328Z, creationTime: 2019-11-20T13:13:13.074328Z, isRegularFile: false, isDirectory: true, isSymbolicLink: false, isOther: false, size: 0, fileKey: null)
19:13:13.651 [Thread-3] TRACE o.c.f.fuse.locks.DataRLockImpl - Released read data lock for '[]'
19:13:13.651 [Thread-3] TRACE o.c.f.fuse.locks.PathRLockImpl - Released read path lock for '[]'
19:13:15.576 [main] INFO  pt.ipb.pdinfs.Main - Mounted successfully. Enter anything to stop the server…

I’m puzzled… I’m sure it is something easy, although it is escaping my eye…

Thank you very much,

/rp

**Comment by xiptos** [comment]
I think the problem is with OSX Fuse… in Linux it works perfectly…

/rp

**Comment by overheadhunter** [comment]
We're also using osxfuse here... Does it work, when you just mirror a normal directory (`Paths.get("/Users/foo/Desktop/bar")`) instead of your `pdinfs:mem:` file system?

**Comment by xiptos** [comment]
Yes… it works fine, mirroring a directory.
So the problem is of my code. 

/rp
