### ISSUE TITLE
File handles are not always released under Windows

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/fuse-nio-adapter#4]
From the WinFSP 2017.2 debug logs we can see that close is called:

```
javaw[TID=0f80]: FFFFDB82FA6F0D90: >>Create [UT---C] "\", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=000000000000054C[PID=1364], DesiredAccess=80, GrantedAccess=0, ShareAccess=7
javaw[TID=0f80]: FFFFDB82FA6F0D90: <<Create IoStatus=0[1] UserContext=0000000000000000:0000000002933290, GrantedAccess=80, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:1000, FileSize=0:1000, CreationTime=2017-12-07T09:10:54.326Z, LastAccessTime=2017-12-13T14:40:48.932Z, LastWriteTime=2017-12-13T14:40:48.932Z, ChangeTime=1970-01-01T00:00:00.000Z, IndexNumber=0:0}
javaw[TID=0f80]: FFFFDB82F9A53010: >>Close 0000000000000000:0000000002933290
javaw[TID=0f80]: FFFFDB82F9A53010: <<Close IoStatus=0[0]
```

However our [release](https://github.com/SerCeMan/jnr-fuse/blob/0.5.1/src/main/java/ru/serce/jnrfuse/FuseFS.java#L214) function is not called (debugger doesn't stop at breakpoint).

@SerCeMan @billziss-gh Does one of you know if:
1. `close`/`release` is skipped under certain conditions?
1. some other functions such as `unlink` expect `release` to be called implicitly? (no such thing is documented in the fuse docs, though)

**Comment by billziss-gh** [comment]
> From the WinFSP 2017.2 debug logs we can see that close is called:
> ```
> javaw[TID=0f80]: FFFFDB82FA6F0D90: >>Create [UT---C] "\", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, > AccessToken=000000000000054C[PID=1364], DesiredAccess=80, GrantedAccess=0, ShareAccess=7
> javaw[TID=0f80]: FFFFDB82FA6F0D90: <<Create IoStatus=0[1] UserContext=0000000000000000:0000000002933290, GrantedAccess=80, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:1000, FileSize=0:1000, CreationTime=2017-12-07T09:10:54.326Z, LastAccessTime=2017-12-13T14:40:48.932Z, LastWriteTime=2017-12-13T14:40:48.932Z, ChangeTime=1970-01-01T00:00:00.000Z, IndexNumber=0:0}
> javaw[TID=0f80]: FFFFDB82F9A53010: >>Close 0000000000000000:0000000002933290
> javaw[TID=0f80]: FFFFDB82F9A53010: <<Close IoStatus=0[0]
>
> However our release function is not called (debugger doesn't stop at breakpoint).

In this case a directory was opened (`"\"`) so you should see `releasedir` and not `release`.

> 1. close/release is skipped under certain conditions?

`Release` is not skipped, but is often delayed on Windows. The main reason is various caching optimizations that Windows does. For example, a common pattern is for an application to open/close the same file continuously. So when an application closes a file, the OS actually keeps it open and cached, so it does not have to continuously re-prime the cache on every open.

While this is a Windows optimization issue, I have had some file systems that were not happy with keeping thousands of files open for long periods. There is an enhancement request to have WinFsp force such files closed and disallow Windows from keeping files open for long periods of time: billziss-gh/winfsp#104. I will be working on this issue for the `v1.3` timeframe.

BTW, if you want to confirm that these `release` calls are delayed and not lost, you can download a utility called [`RAMMap`](https://docs.microsoft.com/en-us/sysinternals/downloads/rammap), which lets you "empty the standby list". You will suddenly see the "missing" `release` calls.

> some other functions such as unlink expect release to be called implicitly? (no such thing is documented in the fuse docs, though)

`Unlink` on Windows is very different from UNIX. On UNIX `unlink` is a simple file system namespace request. On Windows deleting a file involves actually opening the file, setting a special "disposition" flag on it and then closing it. What you see from a FUSE perspective is: `open`, `unlink`, `release`.

**Comment by overheadhunter** [comment]
Ah yes, we didn't watch for releasedir calls. I was somehow mislead by `FILE_OPEN` and didn't even pay attention to the path.

Also thanks for the detailed insights and the hint regarding RAMMap.

We noticed that when recursively deleting a recently created directory, some files inside of this directory are still opened, preventing deletion of their parent directory. We will continue debugging this. I hope I can post some more details about the execution order later.

**Comment by overheadhunter** [comment]
Ok we found the problem. `open`, `unlink`, `release` failed, because our `release` function falsely checked for file existence (which doesn't make too much sense after deleting it).

**Comment by billziss-gh** [comment]
@overheadhunter glad this got resolved!
