### ISSUE TITLE
macOS: Cannot select FUSE as volume type

### ISSUE THREAD

**Issue by qkielabs** [cryptomator/fuse-nio-adapter#40]
When there is no internet connection, the selection of FUSE as volume Type is not possible. 

The Logs shows this error:
`13:09:31.295 [JavaFX Application Thread] ERROR o.c.frontend.fuse.mount.MacMounter - Could not read /Library/Filesystems/osxfuse.fs/Contents/version.plist to detect version of OSXFUSE.`

The error occurs when the MacMounter class tries to find the version of FUSE. When the method **getVersionString** parses the version.plist file, the DocumentBuilder tries to download the DTD file referenced in the verision.plist file. This ends in a Exception when there is no direct connection to the internet. This will also fail on a system with a automatic proxy discovery.

When the DTD Definition is remove from the version.plist file, the error doesn't occur.

**Comment by overheadhunter** [comment]
Thanks for reporting this and also explaining what causes the problem!
