### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by josephsmendoza** [cryptomator/fuse-nio-adapter#42]
I came here after [this message](https://github.com/SerCeMan/jnr-fuse/issues/91#issuecomment-598107425) but I don't see any examples or how to use this repo

**Comment by overheadhunter** [comment]
I think [MirroringFuseMountTest.java](https://github.com/cryptomator/fuse-nio-adapter/blob/develop/src/test/java/org/cryptomator/frontend/fuse/mount/MirroringFuseMountTest.java) should get you started.

You basically just tell this lib to mount the contents of a `Path` at a given mount point.

**Comment by josephsmendoza** [comment]
I'm trying to implement something similar to Overlay FS, where I would need to save changes to files separately from the original files. It doesn't look like the Path API would allow that by itself. When a file is opened, I would need to read from the same file and write to a different one.
