### ISSUE TITLE
Faulty unit tests for Lockmanager

### ISSUE THREAD

**Issue by infeo** [cryptomator/fuse-nio-adapter#49]
## Description

Two unit tests for resource locking contain a race condition. Both reside inside [`LockManagerTest`](https://github.com/cryptomator/fuse-nio-adapter/blob/develop/src/test/java/org/cryptomator/frontend/fuse/locks/LockManagerTest.java). The bug was encoutered during CI runs ( see https://travis-ci.org/github/cryptomator/fuse-nio-adapter/builds/735702459).

One of the faulty tests is 
https://github.com/cryptomator/fuse-nio-adapter/blob/e14b2f6aefde3697c339edfa1758ac8ce20f81fa/src/test/java/org/cryptomator/frontend/fuse/locks/LockManagerTest.java#L206-L236

It is unclear what the cause for the bug is, but it needs to be a race condition and _not a timeout_:
```
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.482 s <<< FAILURE! - in org.cryptomator.frontend.fuse.locks.LockManagerTest
[ERROR] testMultipleReadLocks  Time elapsed: 0.067 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <8> but was: <7>
	at org.cryptomator.frontend.fuse.locks.LockManagerTest$DataLockTests.testMultipleReadLocks(LockManagerTest.java:233)
```

**Comment by infeo** [comment]
The current workaround is to disable all tests in the class `LockManagerTest` (done in 6aebc0de9719cf8e53f602a2cf8f58e5d887c410)

**Comment by overheadhunter** [comment]
1. The failed tests is `testMultipleReadLocks()`, but you're referencing `testMultipleWriteLocks()` code here... intentionally?
2. `Assertions.assertTimeoutPreemptively(...)` is good, but the timeout should be higher than the time we assume the tested code to take.
3. wtf did I do here?

**Comment by infeo** [comment]
> The failed tests is testMultipleReadLocks(), but you're referencing testMultipleWriteLocks() code here... intentionally?

My bad, I edited it. Only the two `testMultipleReadLocks()` are affected. (both have the same design and test goal)

**Comment by overheadhunter** [comment]
Ok that makes more sense now. So 7 threads did as expected, while the 8th one wasn't fast enough.

Bad test implementation. 🙈 I should have used barriers instead of timing-based tests here...
