### ISSUE TITLE
Encode filenames using NFD on Macs

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/fuse-nio-adapter#56]
Basically the same as #27 but we need a different solution. The issue is that the mount option `-omodules=iconv,from_code=UTF-8,to_code=UTF-8-MAC` causes issues with Emojis: https://github.com/cryptomator/cryptomator/issues/961

Referencing another issue that boils the issue down to a buggy(?) `iconv`: https://github.com/osxfuse/osxfuse/issues/706#issuecomment-651135367

Proposed solution:

> We resolved this issue by implementing the NFD to NFC conversion in our user-space code instead of using the built-in iconv module.

Implementing the NFC/NFD conversion in Java instead of instructing it via a mount option.

**Comment by overheadhunter** [comment]
I don't like the "from" and "to" parameters in iconv. Instead I'd like to suggest to add two (optional) configuration parameters to our adapter:

1. The `desiredFilenameEncoding` used when displaying filenames via FUSE (which can be UTF8-NFD for macOS)
2. The `internalFilenameEncoding` used with the NIO-API (which should normally be UTF8-NFC)

![transcode](https://user-images.githubusercontent.com/1204330/109796734-d20c1a80-7c18-11eb-8272-5724507247a0.png)
