### ISSUE TITLE
rename: Failing if file exist - Possible change to just overwrite existing one?

### ISSUE THREAD

**Issue by infeo** [cryptomator/fuse-nio-adapter#8]
## Basic Info
OS: independent
fuse-nio-adapter: commit 943c430ce207c1e0986db4eee54ab2035d82675a 

## Description
If you want to rename a file into an already existing one, it throws an error (File already exist)

## Suggestion
Change this behaviour to just overwriting the existing file.

## Background info
Some programs (e.g. gedit) need this to save an edited file. At first they create a temporary file, read the content of the original file into the tmp-file and in the save process they just rename the tmp-file into the original one.

**Comment by overheadhunter** [comment]
Overwriting seems correct to me.

From [rename(2)](http://man7.org/linux/man-pages/man2/rename.2.html):

> If _newpath_ already exists, it will be atomically replaced

and for directories:

> _oldpath_ can specify a directory.  In this case, _newpath_ must either not exist, or it must specify an empty directory

**Comment by overheadhunter** [comment]
Noteworthy: FUSE 3.x.x introduced [additional flags in the rename function](https://github.com/libfuse/libfuse/blob/fuse-3.2.1/include/fuse.h#L348):

> If RENAME_NOREPLACE is specified, the filesystem must not overwrite _newname_ if it exists and return an error instead.

**Comment by infeo** [comment]
which we cannot use currently, because on the one side jnr-fuse does not support them and on the other underlying winfsp-version just supports fuse 2.x (see [here](https://github.com/cryptomator/fuse-nio-adapter/issues/3) in a comment of billziss-gh).
